### ISSUE TITLE
Multiple seconds stutter when eating food

### ISSUE THREAD

**Issue by FurretUber** [MFHKiwi/super-smash-aeugh#7]
I noticed that, when I eat food, the game may stutter for a while: it may be for less than one second, but it may stutter even for multiple seconds. The first :carrot: eaten caused a 2 seconds stutter, then it went smoothly but then it started stuttering again. The easiest way I found to reproduce this is when three carrots appear close one to another: the third one has a high probability of causing a stutter.

I tried replacing the default `eat.wav` with a much larger wav file, and this increased how long the stutter lasted, so this seems related to the loading of the eat sound. This seems a bit counter-intuitive to me, as the sound effect should be within the executable, so there shouldn't be file loading involved.

The game is on a 5400 RPM HDD, which is a relatively slow storage (but the fastest one I have...), OS is Xubuntu 20.04.

**Comment by MFHKiwi** [comment]
I'm already aware of this issue, but I haven't looked at fixing it. All asset files are embedded in the executable at compile time, so they sit in RAM, and storage speed should make no difference to how the game runs. I'll leave this issue open until this has been figured out.

**Comment by MFHKiwi** [comment]
I have fixed this bug in commit fbf684d98c2bbe689ed805ccd0b0c944474b4080. I was already suspicious of what was causing this, and I turned out to be right. The function that I made to generate the random location for the carrot runs `srand(time(NULL);` to seed the random number generator. This is only supposed to run *once* and pauses the loop until it's finished. I've modified the function that generates the random number to only seed the generator the first time it's run, which should have solved this issue. Thank you for reporting this and actually putting it in my priorities.
